const allQuestions = [
  // --- カテゴリ: テクノロジー ---
  { category: "テクノロジー", difficulty: 1, question: "PCとは何の略称？", answers: ["パーソナルコンピュータ", "プライベートチップ", "パワーキャパシタ", "プロセスコントロール"], correctIndex: 0 },
  { category: "テクノロジー", difficulty: 1, question: "インターネットでウェブページを見るためのソフトウェアを何という？", answers: ["ウェブブラウザ", "ワープロ", "OS", "検索エンジン"], correctIndex: 0 },
  { category: "テクノロジー", difficulty: 1, question: "キーボードで文字をすべて大文字で入力したい時に押すキーは？", answers: ["Caps Lock", "Shift", "Tab", "Alt"], correctIndex: 0 },
  { category: "テクノロジー", difficulty: 1, question: "Apple社が開発したスマートフォンのシリーズ名は？", answers: ["iPhone", "Galaxy", "Xperia", "Pixel"], correctIndex: 0 },
  { category: "テクノロジー", difficulty: 1, question: "コンピュータの頭脳にあたる部分を何という？", answers: ["CPU", "GPU", "RAM", "SSD"], correctIndex: 0 },
  { category: "テクノロジー", difficulty: 1, question: "Eメールの「E」は何の略？", answers: ["Electronic", "Easy", "Express", "Emergency"], correctIndex: 0 },
  { category: "テクノロジー", difficulty: 1, question: "USBは何の略称？", answers: ["ユニバーサル・シリアル・バス", "ウルトラ・サウンド・ビート", "ユナイテッド・システム・ブロック", "アンダー・スクリーン・ボード"], correctIndex: 0 },
  { category: "テクノロジー", difficulty: 1, question: "文書や画像を印刷する装置を何という？", answers: ["プリンター", "スキャナー", "モニター", "プロジェクター"], correctIndex: 0 },
  { category: "テクノロジー", difficulty: 1, question: "無線でインターネットに接続する技術を何という？", answers: ["Wi-Fi", "Bluetooth", "Ethernet", "NFC"], correctIndex: 0 },
  { category: "テクノロジー", difficulty: 1, question: "SNSは何の略？", answers: ["ソーシャル・ネットワーキング・サービス", "スーパー・ネットワーク・システム", "セキュア・ナンバー・サービス", "システム・ノード・セキュリティ"], correctIndex: 0 },
  { category: "テクノロジー", difficulty: 2, question: "ウェブページを記述するためのマークアップ言語は何？", answers: ["HTML", "Python", "Java", "C++"], correctIndex: 0 },
  { category: "テクノロジー", difficulty: 2, question: "コンピュータのデータを一時的に記憶する装置は？", answers: ["RAM", "ROM", "HDD", "CPU"], correctIndex: 0 },
  { category: "テクノロジー", difficulty: 2, question: "世界最大の動画共有サービスは何？", answers: ["YouTube", "Vimeo", "TikTok", "Twitch"], correctIndex: 0 },
  { category: "テクノロジー", difficulty: 2, question: "SNS「Twitter」の現在の名称は？", answers: ["X", "Threads", "BlueSky", "Mastodon"], correctIndex: 0 },
  { category: "テクノロジー", difficulty: 2, question: "オープンソースのOSで、ペンギンのキャラクターが有名なのは？", answers: ["Linux", "Windows", "macOS", "Android"], correctIndex: 0 },
  { category: "テクノロジー", difficulty: 2, question: "画像のファイル形式でないものはどれ？", answers: ["MP3", "JPEG", "PNG", "GIF"], correctIndex: 0 },
  { category: "テクノロジー", difficulty: 2, question: "ウェブサイトのアドレスの最初に来る「https」の「s」は何を意味する？", answers: ["Secure", "System", "Server", "Standard"], correctIndex: 0 },
  { category: "テクノロジー", difficulty: 2, question: "PDFは何の略？", answers: ["ポータブル・ドキュメント・フォーマット", "パーソナル・データ・ファイル", "プリンタブル・デザイン・フォーマット", "プログラマブル・デジタル・ファクト"], correctIndex: 0 },
  { category: "テクノロジー", difficulty: 3, question: "IPアドレスの「IP」とは何の略？", answers: ["インターネット・プロトコル", "インターナル・プロセッサ", "インフォメーション・ポイント", "インテリジェント・パワー"], correctIndex: 0 },
  { category: "テクノロジー", difficulty: 3, question: "Googleが開発したモバイル向けOSは？", answers: ["Android", "iOS", "Windows Mobile", "Symbian"], correctIndex: 0 },
  { category: "テクノロジー", difficulty: 3, question: "ビットコインなどの暗号資産の基盤技術となっているのは？", answers: ["ブロックチェーン", "クラウドコンピューティング", "人工知能", "量子コンピュータ"], correctIndex: 0 },
  { category: "テクノロジー", difficulty: 3, question: "世界で最初に「World Wide Web」を考案した人物は？", answers: ["ティム・バーナーズ＝リー", "ビル・ゲイツ", "スティーブ・ジョブズ", "リーナス・トーバルズ"], correctIndex: 0 },
  { category: "テクノロジー", difficulty: 3, question: "プログラミング言語Pythonの生みの親は？", answers: ["グイド・ヴァン・ロッサム", "ジェームズ・ゴスリン", "ブレンダン・アイク", "ラリー・ウォール"], correctIndex: 0 },
  { category: "テクノロジー", difficulty: 3, question: "コンピュータの性能を表す単位「FLOPS」の「F」は何の略？", answers: ["Floating-point", "Fast", "Function", "File"], correctIndex: 0 },
  { category: "テクノロジー", difficulty: 3, question: "ウェブサイトの見た目やデザインを定義する言語は？", answers: ["CSS", "JavaScript", "PHP", "SQL"], correctIndex: 0 },
  { category: "テクノロジー", difficulty: 3, question: "SaaSとは何の略？", answers: ["Software as a Service", "System as a Software", "Security as a Service", "Sales as a Service"], correctIndex: 0 },
  { category: "テクノロジー", difficulty: 4, question: "コンピュータウイルスの「トロイの木馬」の名前の由来となったのは？", answers: ["ギリシャ神話", "ローマ神話", "北欧神話", "エジプト神話"], correctIndex: 0 },
  { category: "テクノロジー", difficulty: 4, question: "TCP/IPの4階層モデルに含まれない層はどれ？", answers: ["セッション層", "アプリケーション層", "トランスポート層", "インターネット層"], correctIndex: 0 },
  { category: "テクノロジー", difficulty: 4, question: "イーサリアムのスマートコントラクトを記述するためによく使われる言語は？", answers: ["Solidity", "Rust", "Go", "Kotlin"], correctIndex: 0 },
  { category: "テクノロジー", difficulty: 4, question: "アラン・チューリングが考案した、機械が人間的かを判定するテストは？", answers: ["チューリング・テスト", "ミラー・テスト", "ベイズ・テスト", "中国語の部屋"], correctIndex: 0 },
  { category: "テクノロジー", difficulty: 4, question: "JPEG圧縮で使われる主要な数学的変換は何？", answers: ["離散コサイン変換", "高速フーリエ変換", "ウェーブレット変換", "ラプラス変換"], correctIndex: 0 },
  { category: "テクノロジー", difficulty: 4, question: "C言語を開発した人物は？", answers: ["デニス・リッチー", "ケン・トンプソン", "ブライアン・カーニハン", "ビル・ゲイツ"], correctIndex: 0 },
  { category: "テクノロジー", difficulty: 5, question: "最初のコンピュータバグは、物理的に何が原因だったとされている？", answers: ["蛾", "ゴキブリ", "ネズミ", "ホコリ"], correctIndex: 0 },
  { category: "テクノロジー", difficulty: 5, question: "UNIXタイムスタンプの起点となる「エポック」は西暦何年1月1日？", answers: ["1970年", "1980年", "1960年", "2000年"], correctIndex: 0 },
  { category: "テクノロジー", difficulty: 5, question: "Intel 4004が世界初の商用マイクロプロセッサとして登場したのは何年？", answers: ["1971年", "1969年", "1975年", "1981年"], correctIndex: 0 },
  { category: "テクノロジー", difficulty: 5, question: "ムーアの法則が提唱する、半導体集積回路の性能が2倍になる期間は？", answers: ["18ヶ月（1.5年）", "12ヶ月（1年）", "24ヶ月（2年）", "36ヶ月（3年）"], correctIndex: 0 },

  // --- カテゴリ: 歴史 ---
  { category: "歴史", difficulty: 1, question: "日本の初代内閣総理大臣は誰？", answers: ["伊藤博文", "大久保利通", "坂本龍馬", "西郷隆盛"], correctIndex: 0 },
  { category: "歴史", difficulty: 1, question: "エジプトにある巨大な王の墓を何という？", answers: ["ピラミッド", "ジグラット", "コロッセオ", "パルテノン神殿"], correctIndex: 0 },
  { category: "歴史", difficulty: 1, question: "アメリカ大陸を発見したとされる探検家は？", answers: ["コロンブス", "マゼラン", "ヴァスコ・ダ・ガマ", "マルコ・ポーロ"], correctIndex: 0 },
  { category: "歴史", difficulty: 1, question: "日本の戦国時代を終わらせ、天下統一を成し遂げた武将は？", answers: ["豊臣秀吉", "織田信長", "徳川家康", "武田信玄"], correctIndex: 0 },
  { category: "歴史", difficulty: 1, question: "フランス革命のスローガンとして掲げられた3つの言葉は「自由、平等、あと一つは？」", answers: ["博愛", "友愛", "正義", "団結"], correctIndex: 0 },
  { category: "歴史", difficulty: 1, question: "第二次世界大戦が終わった年は？", answers: ["1945年", "1939年", "1918年", "1950年"], correctIndex: 0 },
  { category: "歴史", difficulty: 1, question: "日本で武士が政治を行っていた時代を大きく分けて、鎌倉、室町、安土桃山と何時代？", answers: ["江戸時代", "平安時代", "奈良時代", "明治時代"], correctIndex: 0 },
  { category: "歴史", difficulty: 2, question: "古代ローマ帝国で最初の皇帝となった人物は誰？", answers: ["アウグストゥス", "ユリウス・カエサル", "ネロ", "トラヤヌス"], correctIndex: 0 },
  { category: "歴史", difficulty: 2, question: "マルティン・ルターが始めたキリスト教の改革運動を何という？", answers: ["宗教改革", "ルネサンス", "十字軍", "啓蒙思想"], correctIndex: 0 },
  { category: "歴史", difficulty: 2, question: "江戸幕府を開いた人物は？", answers: ["徳川家康", "徳川秀忠", "徳川家光", "徳川吉宗"], correctIndex: 0 },
  { category: "歴史", difficulty: 2, question: "万里の長城を建設し始めた中国の最初の皇帝は？", answers: ["始皇帝", "劉邦", "武帝", "玄宗"], correctIndex: 0 },
  { category: "歴史", difficulty: 2, question: "1969年、人類で初めて月面に降り立った宇宙飛行士は？", answers: ["ニール・アームストロング", "ユーリイ・ガガーリン", "ジョン・グレン", "バズ・オルドリン"], correctIndex: 0 },
  { category: "歴史", difficulty: 2, question: "100年戦争はどことどこの国の間で戦われた？", answers: ["イギリスとフランス", "スペインとポルトガル", "ドイツとロシア", "オーストリアとプロイセン"], correctIndex: 0 },
  { category: "歴史", difficulty: 2, question: "1989年に崩壊した、東西ドイツを隔てていた壁は？", answers: ["ベルリンの壁", "ハドリアヌスの壁", "万里の長城", "嘆きの壁"], correctIndex: 0 },
  { category: "歴史", difficulty: 2, question: "日本の元号で「平成」の次は何？", answers: ["令和", "昭和", "大正", "明治"], correctIndex: 0 },
  { category: "歴史", difficulty: 3, question: "古代メソポタミア文明で制定された、「目には目を、歯には歯を」で知られる法典は？", answers: ["ハンムラビ法典", "十二表法", "ローマ法大全", "リピト・イシュタル法典"], correctIndex: 0 },
  { category: "歴史", difficulty: 3, question: "1453年にオスマン帝国によって滅ぼされた東ローマ帝国の首都はどこ？", answers: ["コンスタンティノープル", "ローマ", "アテネ", "アンティオキア"], correctIndex: 0 },
  { category: "歴史", difficulty: 3, question: "明治維新の「五箇条の御誓文」が発布された年は？", answers: ["1868年", "1853年", "1877年", "1889年"], correctIndex: 0 },
  { category: "歴史", difficulty: 3, question: "産業革命が最初に起こった国はどこ？", answers: ["イギリス", "ドイツ", "アメリカ", "フランス"], correctIndex: 0 },
  { category: "歴史", difficulty: 3, question: "古代ギリシャの哲学者で、「ソクラテスの弟子」であり、「アリストテレスの師」である人物は？", answers: ["プラトン", "ピタゴラス", "ヘラクレイトス", "デモクリトス"], correctIndex: 0 },
  { category: "歴史", difficulty: 3, question: "1929年に始まった世界的な経済危機を何という？", answers: ["世界恐慌", "オイルショック", "ブラックマンデー", "アジア通貨危機"], correctIndex: 0 },
  { category: "歴史", difficulty: 3, question: "マケドニアのアレクサンドロス大王の家庭教師を務めた哲学者は？", answers: ["アリストテレス", "プラトン", "ソクラテス", "ディオゲネス"], correctIndex: 0 },
  { category: "歴史", difficulty: 4, question: "インカ帝国を征服したスペインのコンキスタドールは誰？", answers: ["フランシスコ・ピサロ", "エルナン・コルテス", "バスコ・ヌーニェス・デ・バルボア", "フェルディナンド・マゼラン"], correctIndex: 0 },
  { category: "歴史", difficulty: 4, question: "ロシア革命を指導し、ソビエト連邦の初代指導者となった人物は？", answers: ["ウラジーミル・レーニン", "ヨシフ・スターリン", "レフ・トロツキー", "ミハイル・ゴルバチョフ"], correctIndex: 0 },
  { category: "歴史", difficulty: 4, question: "古代エジプトで使われていた神聖文字を何という？", answers: ["ヒエログリフ", "楔形文字", "線文字B", "甲骨文字"], correctIndex: 0 },
  { category: "歴史", difficulty: 4, question: "ナポレオン・ボナパルトが最終的に敗北した戦いは？", answers: ["ワーテルローの戦い", "トラファルガーの海戦", "ライプツィヒの戦い", "アウステルリッツの戦い"], correctIndex: 0 },
  { category: "歴史", difficulty: 4, question: "ジャンヌ・ダルクが活躍した戦争は何？", answers: ["百年戦争", "三十年戦争", "薔薇戦争", "十字軍"], correctIndex: 0 },
  { category: "歴史", difficulty: 4, question: "モンゴル帝国を築いた人物は？", answers: ["チンギス・ハン", "フビライ・ハン", "オゴデイ・ハン", "ティムール"], correctIndex: 0 },
  { category: "歴史", difficulty: 5, question: "ロゼッタストーンに刻まれていた3種類の文字のうち、含まれていないのはどれ？", answers: ["楔形文字", "ヒエログリフ", "デモティック", "ギリシャ文字"], correctIndex: 0 },
  { category: "歴史", difficulty: 5, question: "三十年戦争を終結させた講和条約は何？", answers: ["ヴェストファーレン条約", "ウィーン条約", "ヴェルサイユ条約", "ユトレヒト条約"], correctIndex: 0 },
  { category: "歴史", difficulty: 5, question: "古代ローマの政治家カエサルがガリア遠征について記した著作のタイトルは？", answers: ["ガリア戦記", "内乱記", "ゲルマニア", "国家論"], correctIndex: 0 },

  // --- カテゴリ: 科学 ---
  { category: "科学", difficulty: 1, question: "水が気体になったものを何という？", answers: ["水蒸気", "氷", "酸素", "雲"], correctIndex: 0 },
  { category: "科学", difficulty: 1, question: "地球が太陽の周りを一周するのにかかる時間は約何日？", answers: ["365日", "30日", "24日", "7日"], correctIndex: 0 },
  { category: "科学", difficulty: 1, question: "人間の血液型で、存在しないのはどれ？", answers: ["C型", "A型", "B型", "O型"], correctIndex: 0 },
  { category: "科学", difficulty: 1, question: "元素記号「H」が表す元素は何？", answers: ["水素", "ヘリウム", "窒素", "酸素"], correctIndex: 0 },
  { category: "科学", difficulty: 1, question: "太陽系の惑星で、最も太陽に近いのは？", answers: ["水星", "金星", "地球", "火星"], correctIndex: 0 },
  { category: "科学", difficulty: 1, question: "植物が光を使って栄養を作る働きを何という？", answers: ["光合成", "呼吸", "蒸散", "分解"], correctIndex: 0 },
  { category: "科学", difficulty: 1, question: "磁石の持つ、鉄などを引きつける力のことを何という？", answers: ["磁力", "重力", "電力", "引力"], correctIndex: 0 },
  { category: "科学", difficulty: 1, question: "虹は何色に見える？", answers: ["7色", "6色", "8色", "無限の色"], correctIndex: 0 },
  { category: "科学", difficulty: 2, question: "音の速さ（音速）は、空気中でおよそ秒速何メートル？", answers: ["340m", "100m", "1000m", "光速と同じ"], correctIndex: 0 },
  { category: "科学", difficulty: 2, question: "物質の三態とは、固体、液体とあと一つは何？", answers: ["気体", "プラズマ", "真空", "イオン"], correctIndex: 0 },
  { category: "科学", difficulty: 2, question: "「万有引力の法則」を発見した科学者は誰？", answers: ["アイザック・ニュートン", "アルベルト・アインシュタイン", "ガリレオ・ガリレイ", "マリー・キュリー"], correctIndex: 0 },
  { category: "科学", difficulty: 2, question: "生物の設計図と言われる、遺伝情報を担う物質は？", answers: ["DNA", "RNA", "ATP", "タンパク質"], correctIndex: 0 },
  { category: "科学", difficulty: 2, question: "元素記号「Fe」が表す元素は何？", answers: ["鉄", "金", "銀", "銅"], correctIndex: 0 },
  { category: "科学", difficulty: 2, question: "私たちの銀河系の名前は何？", answers: ["天の川銀河", "アンドロメダ銀河", "さんかく座銀河", "大マゼラン雲"], correctIndex: 0 },
  { category: "科学", difficulty: 2, question: "蝶が、幼虫からさなぎを経て成虫になる変化を何という？", answers: ["変態", "進化", "成長", "羽化"], correctIndex: 0 },
  { category: "科学", difficulty: 2, question: "音を伝えるものがない真空の宇宙空間では、音は聞こえる？聞こえない？", answers: ["聞こえない", "聞こえる", "小さく聞こえる", "場合による"], correctIndex: 0 },
  { category: "科学", difficulty: 2, question: "「細胞の発電所」と呼ばれる細胞小器官は？", answers: ["ミトコンドリア", "核", "リボソーム", "ゴルジ体"], correctIndex: 0 },
  { category: "科学", difficulty: 3, question: "相対性理論を提唱した科学者は誰？", answers: ["アルベルト・アインシュタイン", "ニールス・ボーア", "エルヴィン・シュレーディンガー", "ヴェルナー・ハイゼンベルク"], correctIndex: 0 },
  { category: "科学", difficulty: 3, question: "pHが7のとき、その液体は何性？", answers: ["中性", "酸性", "アルカリ性", "塩基性"], correctIndex: 0 },
  { category: "科学", difficulty: 3, question: "恐竜が絶滅したと考えられている、約6600万年前に終わった地質時代は？", answers: ["白亜紀", "ジュラ紀", "三畳紀", "古第三紀"], correctIndex: 0 },
  { category: "科学", difficulty: 3, question: "メンデルが遺伝の法則を発見するために用いた植物は何？", answers: ["エンドウマメ", "アサガオ", "トウモロコシ", "ショウジョウバエ"], correctIndex: 0 },
  { category: "科学", difficulty: 3, question: "大気の約78%を占める最も多い気体は何？", answers: ["窒素", "酸素", "アルゴン", "二酸化炭素"], correctIndex: 0 },
  { category: "科学", difficulty: 3, question: "光の速さは真空中で秒速約何キロメートル？", answers: ["30万km", "15万km", "50万km", "10万km"], correctIndex: 0 },
  { category: "科学", difficulty: 3, question: "太陽系の惑星のうち、美しい環を持つことで知られるのは？", answers: ["土星", "木星", "天王星", "海王星"], correctIndex: 0 },
  { category: "科学", difficulty: 3, question: "地球の核の主成分は何と何？", answers: ["鉄とニッケル", "ケイ素と酸素", "アルミニウムとマグネシウム", "水素とヘリウム"], correctIndex: 0 },
  { category: "科学", difficulty: 4, question: "原子核を構成する粒子は、陽子と何？", answers: ["中性子", "電子", "光子", "クォーク"], correctIndex: 0 },
  { category: "科学", difficulty: 4, question: "ペニシリンを発見した科学者は誰？", answers: ["アレクサンダー・フレミング", "ルイ・パスツール", "ロベルト・コッホ", "ジョゼフ・リスター"], correctIndex: 0 },
  { category: "科学", difficulty: 4, question: "光年とは何の単位？", answers: ["距離", "時間", "速さ", "明るさ"], correctIndex: 0 },
  { category: "科学", difficulty: 4, question: "元素周期表を作成し、未発見の元素の存在を予言したロシアの化学者は？", answers: ["ドミトリ・メンデレーエフ", "アントワーヌ・ラボアジエ", "ジョン・ドルトン", "アメデオ・アヴォガドロ"], correctIndex: 0 },
  { category: "科学", difficulty: 4, question: "物体の温度の下限とされる「絶対零度」は摂氏何℃？", answers: ["-273.15℃", "0℃", "-100℃", "-459.67℃"], correctIndex: 0 },
  { category: "科学", difficulty: 4, question: "人間の体で最も大きい臓器は？", answers: ["皮膚", "肝臓", "脳", "肺"], correctIndex: 0 },
  { category: "科学", difficulty: 5, question: "すべての素粒子を記述する現代物理学の理論を何という？", answers: ["標準模型", "超ひも理論", "ループ量子重力理論", "万物の理論"], correctIndex: 0 },
  { category: "科学", difficulty: 5, question: "シュレーディンガーの猫の思考実験が問いかけるのは、何の奇妙さ？", answers: ["量子力学", "相対性理論", "熱力学", "電磁気学"], correctIndex: 0 },
  { category: "科学", difficulty: 5, question: "宇宙の始まりとされる大爆発の理論を何という？", answers: ["ビッグバン理論", "定常宇宙論", "インフレーション理論", "サイクリック宇宙論"], correctIndex: 0 },

  // --- カテゴリ: ポップカルチャー ---
  { category: "ポップカルチャー", difficulty: 1, question: "映画「スター・ウォーズ」シリーズに登場する、ジェダイが使う光る剣の名前は？", answers: ["ライトセーバー", "ビームサーベル", "フォースブレード", "エナジーソード"], correctIndex: 0 },
  { category: "ポップカルチャー", difficulty: 1, question: "任天堂のゲームに登場する、配管工の兄弟といえばマリオと誰？", answers: ["ルイージ", "ワリオ", "クッパ", "ピーチ"], correctIndex: 0 },
  { category: "ポップカルチャー", difficulty: 1, question: "世界中で大ヒットしたJ.K.ローリングの小説シリーズは何？", answers: ["ハリー・ポッター", "指輪物語", "ナルニア国物語", "ゲド戦記"], correctIndex: 0 },
  { category: "ポップカルチャー", difficulty: 1, question: "映画「タイタニック」で主演を務めた男性俳優は誰？", answers: ["レオナルド・ディカプリオ", "トム・クルーズ", "ブラッド・ピット", "ジョニー・デップ"], correctIndex: 0 },
  { category: "ポップカルチャー", difficulty: 1, question: "アニメ「ドラゴンボール」の主人公は誰？", answers: ["孫悟空", "ベジータ", "ピッコロ", "孫悟飯"], correctIndex: 0 },
  { category: "ポップカルチャー", difficulty: 1, question: "イギリス出身の伝説的なロックバンドで、「Let It Be」などの名曲で知られるのは？", answers: ["ザ・ビートルズ", "クイーン", "ローリング・ストーンズ", "レッド・ツェッペリン"], correctIndex: 0 },
  { category: "ポップカルチャー", difficulty: 1, question: "ポケットモンスターで、主人公サトシの最初のパートナーは何？", answers: ["ピカチュウ", "フシギダネ", "ヒトカゲ", "ゼニガメ"], correctIndex: 0 },
  { category: "ポップカルチャー", difficulty: 2, question: "映画「バック・トゥ・ザ・フューチャー」でタイムマシンとして改造された車の名前は？", answers: ["デロリアン", "ポンティアック・ファイヤーバード", "シボレー・カマロ", "フォード・マスタング"], correctIndex: 0 },
  { category: "ポップカルチャー", difficulty: 2, question: "スタジオジブリの映画「となりのトトロ」の監督は誰？", answers: ["宮崎駿", "高畑勲", "鈴木敏夫", "庵野秀明"], correctIndex: 0 },
  { category: "ポップカルチャー", difficulty: 2, question: "ゲーム「マインクラフト」で、プレイヤーに敵対的な緑色のキャラクターは何？", answers: ["クリーパー", "エンダーマン", "ゾンビ", "スケルトン"], correctIndex: 0 },
  { category: "ポップカルチャー", difficulty: 2, question: "1990年代に社会現象となったロボットアニメで、「A.T.フィールド」という用語が登場するのは？", answers: ["新世紀エヴァンゲリオン", "機動戦士ガンダム", "マクロス", "コードギアス"], correctIndex: 0 },
  { category: "ポップカルチャー", difficulty: 2, question: "「キング・オブ・ポップ」と称されたアメリカの歌手は誰？", answers: ["マイケル・ジャクソン", "プリンス", "エルヴィス・プレスリー", "フレディ・マーキュリー"], correctIndex: 0 },
  { category: "ポップカルチャー", difficulty: 2, question: "漫画「ONE PIECE」の作者は誰？", answers: ["尾田栄一郎", "岸本斉史", "鳥山明", "冨樫義博"], correctIndex: 0 },
  { category: "ポップカルチャー", difficulty: 2, question: "1980年代に一世を風靡した、ルービックキューブは何種類の色の面で構成されている？", answers: ["6色", "4色", "8色", "12色"], correctIndex: 0 },
  { category: "ポップカルチャー", difficulty: 2, question: "映画「ジュラシック・パーク」シリーズの監督は誰？", answers: ["スティーヴン・スピルバーグ", "ジョージ・ルーカス", "ジェームズ・キャメロン", "クリストファー・ノーラン"], correctIndex: 0 },
  { category: "ポップカルチャー", difficulty: 3, question: "映画監督クエンティン・タランティーノのデビュー作は？", answers: ["レザボア・ドッグス", "パルプ・フィクション", "キル・ビル", "ジャッキー・ブラウン"], correctIndex: 0 },
  { category: "ポップカルチャー", difficulty: 3, question: "日本の家庭用ゲーム機「ファミリーコンピュータ」が発売された年は？", answers: ["1983年", "1980年", "1985年", "1990年"], correctIndex: 0 },
  { category: "ポップカルチャー", difficulty: 3, question: "1982年の映画「ブレードランナー」の原作となったフィリップ・K・ディックの小説名は？", answers: ["アンドロイドは電気羊の夢を見るか？", "高い城の男", "ユービック", "マイノリティ・リポート"], correctIndex: 0 },
  { category: "ポップカルチャー", difficulty: 3, question: "ヒップホップ音楽の三大要素と呼ばれるのは、DJ、MCと何？", answers: ["ブレイクダンス", "グラフィティ", "ラップ", "サンプリング"], correctIndex: 0 },
  { category: "ポップカルチャー", difficulty: 3, question: "ゲーム「ファイナルファンタジーVII」の主人公の名前は？", answers: ["クラウド・ストライフ", "スコール・レオンハート", "ジタン・トライバル", "ティーダ"], correctIndex: 0 },
  { category: "ポップカルチャー", difficulty: 3, question: "アカデミー賞で作品賞を受賞した初のアジア映画は？", answers: ["パラサイト 半地下の家族", "グリーン・デスティニー", "スラムドッグ$ミリオネア", "万引き家族"], correctIndex: 0 },
  { category: "ポップカルチャー", difficulty: 3, question: "漫画「AKIRA」の作者は誰？", answers: ["大友克洋", "士郎正宗", "宮崎駿", "押井守"], correctIndex: 0 },
  { category: "ポップカルチャー", difficulty: 3, question: "ゲーム「ゼルダの伝説」シリーズで、主人公の名前は？", answers: ["リンク", "ゼルダ", "ガノン", "インパ"], correctIndex: 0 },
  { category: "ポップカルチャー", difficulty: 3, question: "映画「マトリックス」で、ネオが選んだピルの色は？", answers: ["赤", "青", "緑", "黄"], correctIndex: 0 },
  { category: "ポップカルチャー", difficulty: 4, question: "デヴィッド・リンチ監督のTVシリーズ「ツイン・ピークス」で、物語の中心となる事件の被害者は誰？", answers: ["ローラ・パーマー", "オードリー・ホーン", "ドナ・ヘイワード", "シェリー・ジョンソン"], correctIndex: 0 },
  { category: "ポップカルチャー", difficulty: 4, question: "世界で初めて作られた長編CGアニメーション映画は何？", answers: ["トイ・ストーリー", "シュレック", "ファインディング・ニモ", "カーズ"], correctIndex: 0 },
  { category: "ポップカルチャー", difficulty: 4, question: "任天堂のゲーム機「NINTENDO64」のコントローラーで特徴的だった点は？", answers: ["3Dスティック", "タッチスクリーン", "モーションセンサー", "振動機能"], correctIndex: 0 },
  { category: "ポップカルチャー", difficulty: 4, question: "アルバム「Nevermind」でグランジ・ロックを世界的に有名にしたバンドは？", answers: ["ニルヴァーナ", "パール・ジャム", "サウンドガーデン", "アリス・イン・チェインズ"], correctIndex: 0 },
  { category: "ポップカルチャー", difficulty: 4, question: "ビートルズが最後に観客の前で行ったライブ（ルーフトップ・コンサート）は何年？", answers: ["1969年", "1966年", "1970年", "1968年"], correctIndex: 0 },
  { category: "ポップカルチャー", difficulty: 4, question: "バンド「クイーン」のボーカリストは誰？", answers: ["フレディ・マーキュリー", "ブライアン・メイ", "ロジャー・テイラー", "ジョン・ディーコン"], correctIndex: 0 },
  { category: "ポップカルチャー", difficulty: 5, question: "世界初のアーケードビデオゲームと言われているのは？", answers: ["Computer Space", "Pong", "Space Invaders", "Pac-Man"], correctIndex: 0 },
  { category: "ポップカルチャー", difficulty: 5, question: "映画「2001年宇宙の旅」で反乱を起こすAIコンピュータの名前は？", answers: ["HAL 9000", "Skynet", "GLaDOS", "VIKI"], correctIndex: 0 },
  { category: "ポップカルチャー", difficulty: 5, question: "SF作家ウィリアム・ギブスンが小説「ニューロマンサー」で作り出した、仮想空間を指す言葉は？", answers: ["サイバースペース", "マトリックス", "メタバース", "オアシス"], correctIndex: 0 },
  { category: "ポップカルチャー", difficulty: 5, question: "タランティーノ監督の「パルプ・フィクション」のタイトルの意味は？", answers: ["三文小説", "血みどろのフィクション", "オレンジジュース", "運命の交差点"], correctIndex: 0 },

  // --- カテゴリ: 地理 ---
  { category: "地理", difficulty: 1, question: "日本の首都はどこ？", answers: ["東京", "京都", "大阪", "名古屋"], correctIndex: 0 },
  { category: "地理", difficulty: 1, question: "世界で最も面積の大きい国は？", answers: ["ロシア", "カナダ", "中国", "アメリカ"], correctIndex: 0 },
  { category: "地理", difficulty: 1, question: "世界で最も高い山は？", answers: ["エベレスト", "K2", "カンチェンジュンガ", "富士山"], correctIndex: 0 },
  { category: "地理", difficulty: 1, question: "世界最大の砂漠は？", answers: ["サハラ砂漠", "ゴビ砂漠", "アラビア砂漠", "南極大陸"], correctIndex: 0 },
  { category: "地理", difficulty: 1, question: "イタリアの首都はどこ？", answers: ["ローマ", "ミラノ", "ヴェネツィア", "フィレンツェ"], correctIndex: 0 },
  { category: "地理", difficulty: 1, question: "日本で最も大きい湖は？", answers: ["琵琶湖", "霞ヶ浦", "サロマ湖", "猪苗代湖"], correctIndex: 0 },
  { category: "地理", difficulty: 2, question: "世界で最も長い川は？", answers: ["ナイル川", "アマゾン川", "長江", "ミシシッピ川"], correctIndex: 0 },
  { category: "地理", difficulty: 2, question: "世界で最も人口の多い国は？", answers: ["インド", "中国", "アメリカ", "インドネシア"], correctIndex: 0 },
  { category: "地理", difficulty: 2, question: "アフリカ大陸の最南端にある岬の名前は？", answers: ["喜望峰", "ホーン岬", "コモリン岬", "ヴェルデ岬"], correctIndex: 0 },
  { category: "地理", difficulty: 2, question: "グリニッジ標準時が基準としている経線は経度何度の線？", answers: ["0度", "90度", "180度", "45度"], correctIndex: 0 },
  { category: "地理", difficulty: 2, question: "エッフェル塔がある都市は？", answers: ["パリ", "ロンドン", "ニューヨーク", "東京"], correctIndex: 0 },
  { category: "地理", difficulty: 2, question: "ユーラシア大陸とアフリカ大陸を繋ぐ、運河で有名な地峡は？", answers: ["スエズ地峡", "パナマ地峡", "クラ地峡", "カレリア地峡"], correctIndex: 0 },
  { category: "地理", difficulty: 2, question: "カナダの首都はどこ？", answers: ["オタワ", "トロント", "バンクーバー", "モントリオール"], correctIndex: 0 },
  { category: "地理", difficulty: 2, question: "カナダの公用語は英語と何？", answers: ["フランス語", "スペイン語", "ドイツ語", "中国語"], correctIndex: 0 },
  { category: "地理", difficulty: 3, question: "世界で唯一、赤道と本初子午線が両方通過する大陸は？", answers: ["アフリカ大陸", "南アメリカ大陸", "アジア大陸", "ヨーロッパ大陸"], correctIndex: 0 },
  { category: "地理", difficulty: 3, question: "アンデス山脈がある大陸は？", answers: ["南アメリカ大陸", "北アメリカ大陸", "アフリカ大陸", "アジア大陸"], correctIndex: 0 },
  { category: "地理", difficulty: 3, question: "世界で最も多くの国と国境を接している国は？", answers: ["中国", "ロシア", "ブラジル", "ドイツ"], correctIndex: 0 },
  { category: "地理", difficulty: 3, question: "日本の47都道府県のうち、海に面していない「内陸県」はいくつある？", answers: ["8つ", "6つ", "10つ", "4つ"], correctIndex: 0 },
  { category: "地理", difficulty: 3, question: "「死海」が位置するのは、ヨルダンとどの国の国境？", answers: ["イスラエル", "エジプト", "シリア", "サウジアラビア"], correctIndex: 0 },
  { category: "地理", difficulty: 3, question: "「自由の女神像」がある都市は？", answers: ["ニューヨーク", "ワシントンD.C.", "ロサンゼルス", "シカゴ"], correctIndex: 0 },
  { category: "地理", difficulty: 4, question: "世界で最も北にある首都は？", answers: ["レイキャビク（アイスランド）", "ヘルシンキ（フィンランド）", "オスロ（ノルウェー）", "オタワ（カナダ）"], correctIndex: 0 },
  { category: "地理", difficulty: 4, question: "国際日付変更線が大きく東に迂回しているのは、どの国の領土を避けるため？", answers: ["キリバス", "フィジー", "トンガ", "サモア"], correctIndex: 0 },
  { category: "地理", difficulty: 4, question: "国土が完全に他のひとつの国に囲まれている「包領国」でないのはどれ？", answers: ["モナコ", "サンマリノ", "バチカン市国", "レソト"], correctIndex: 0 },
  { category: "地理", difficulty: 4, question: "チチカカ湖があるのは、ペルーとどの国の国境？", answers: ["ボリビア", "エクアドル", "チリ", "コロンビア"], correctIndex: 0 },
  { category: "地理", difficulty: 4, question: "世界で2番目に大きい大陸は？", answers: ["アフリカ大陸", "アジア大陸", "北アメリカ大陸", "南アメリカ大陸"], correctIndex: 0 },
  { category: "地理", difficulty: 5, question: "世界に4つある、国名にアルファベットの「X」が含まれる国のうち、アジアにある国は？", answers: ["存在しない", "ウズベキスタン", "カザフスタン", "アゼルバイジャン"], correctIndex: 0 },
  { category: "地理", difficulty: 5, question: "世界で最も標高の高い首都は、ボリビアのラパスですが、憲法上の首都はどこ？", answers: ["スクレ", "サンタクルス", "コチャバンバ", "ポトシ"], correctIndex: 0 },
  { category: "地理", difficulty: 5, question: "世界で最も多くの島を持つ国はどこ？", answers: ["スウェーデン", "インドネシア", "カナダ", "フィンランド"], correctIndex: 0 },

  // --- カテゴリ: 文学・芸術 ---
  { category: "文学・芸術", difficulty: 1, question: "レオナルド・ダ・ヴィンチが描いた、世界で最も有名な肖像画は何？", answers: ["モナ・リザ", "最後の晩餐", "ウィトルウィウス的人体図", "受胎告知"], correctIndex: 0 },
  { category: "文学・芸術", difficulty: 1, question: "「ロミオとジュリエット」の作者であるイギリスの劇作家は誰？", answers: ["ウィリアム・シェイクスピア", "チャールズ・ディケンズ", "ジョージ・オーウェル", "オスカー・ワイルド"], correctIndex: 0 },
  { category: "文学・芸術", difficulty: 1, question: "夏目漱石の小説「吾輩は猫である」の猫には、何がない？", answers: ["名前", "しっぽ", "飼い主", "家"], correctIndex: 0 },
  { category: "文学・芸術", difficulty: 1, question: "ゴッホが描いた、夜空の渦が印象的な作品は何？", answers: ["星月夜", "ひまわり", "夜のカフェテラス", "自画像"], correctIndex: 0 },
  { category: "文学・芸術", difficulty: 1, question: "日本の伝統的な短い詩で、五・七・五の形式を持つものは何？", answers: ["俳句", "短歌", "川柳", "連歌"], correctIndex: 0 },
  { category: "文学・芸術", difficulty: 2, question: "ピカソがスペイン内戦の悲劇を描いた大作の名前は？", answers: ["ゲルニカ", "アヴィニョンの娘たち", "泣く女", "老いたギタリスト"], correctIndex: 0 },
  { category: "文学・芸術", difficulty: 2, question: "「老人と海」でノーベル文学賞を受賞したアメリカの作家は？", answers: ["アーネスト・ヘミングウェイ", "ウィリアム・フォークナー", "F・スコット・フィッツジェラルド", "ジョン・スタインベック"], correctIndex: 0 },
  { category: "文学・芸術", difficulty: 2, question: "ベートーヴェンの交響曲第5番の通称は？", answers: ["運命", "英雄", "田園", "合唱"], correctIndex: 0 },
  { category: "文学・芸術", difficulty: 2, question: "川端康成が日本人として初めてノーベル文学賞を受賞した際の代表作の一つは？", answers: ["雪国", "伊豆の踊子", "千羽鶴", "古都"], correctIndex: 0 },
  { category: "文学・芸術", difficulty: 2, question: "フランスの印象派を代表する画家で、「睡蓮」の連作で有名なのは？", answers: ["クロード・モネ", "エドゥアール・マネ", "ピエール＝オーギュスト・ルノワール", "エドガー・ドガ"], correctIndex: 0 },
  { category: "文学・芸術", difficulty: 3, question: "「人間は考える葦である」という言葉を残したフランスの哲学者・思想家は誰？", answers: ["ブレーズ・パスカル", "ルネ・デカルト", "ジャン＝ジャック・ルソー", "ヴォルテール"], correctIndex: 0 },
  { category: "文学・芸術", difficulty: 3, question: "ムンクの代表作「叫び」が描かれた国はどこ？", answers: ["ノルウェー", "スウェーデン", "デンマーク", "フィンランド"], correctIndex: 0 },
  { category: "文学・芸術", difficulty: 3, question: "ロシアの文豪ドストエフスキーの代表作で、高利貸しの老婆を殺害する青年を描いた小説は？", answers: ["罪と罰", "カラマーゾフの兄弟", "白痴", "悪霊"], correctIndex: 0 },
  { category: "文学・芸術", difficulty: 3, question: "サルバドール・ダリに代表される、夢や無意識の世界を描く芸術運動を何という？", answers: ["シュルレアリスム", "キュビスム", "ダダイスム", "未来派"], correctIndex: 0 },
  { category: "文学・芸術", difficulty: 3, question: "日本の浮世絵師で、「富嶽三十六景」を描いたのは誰？", answers: ["葛飾北斎", "歌川広重", "東洲斎写楽", "喜多川歌麿"], correctIndex: 0 },
  { category: "文学・芸術", difficulty: 3, question: "童話「不思議の国のアリス」の作者は？", answers: ["ルイス・キャロル", "ハンス・クリスチャン・アンデルセン", "グリム兄弟", "シャルル・ペロー"], correctIndex: 0 },
  { category: "文学・芸術", difficulty: 3, question: "村上春樹のデビュー作のタイトルは？", answers: ["風の歌を聴け", "ノルウェイの森", "1973年のピンボール", "羊をめぐる冒険"], correctIndex: 0 },
  { category: "文学・芸術", difficulty: 3, question: "「記憶の固執」を描いたシュルレアリスムの画家は？", answers: ["サルバドール・ダリ", "ルネ・マグリット", "マックス・エルンスト", "ジョアン・ミロ"], correctIndex: 0 },
  { category: "文学・芸術", difficulty: 4, question: "ダンテが「神曲」で描いた地獄、煉獄、天国を旅する案内人の一人、古代ローマの詩人は誰？", answers: ["ウェルギリウス", "ホメロス", "オウィディウス", "ホラティウス"], correctIndex: 0 },
  { category: "文学・芸術", difficulty: 4, question: "バロック音楽を代表する作曲家で、「フーガの技法」など対位法を極めたドイツの音楽家は？", answers: ["ヨハン・ゼバスティアン・バッハ", "ゲオルク・フリードリヒ・ヘンデル", "アントニオ・ヴィヴァルディ", "ヴォルフガング・アマデウス・モーツァルト"], correctIndex: 0 },
  { category: "文学・芸術", difficulty: 4, question: "マルセル・プルーストの長編小説「失われた時を求めて」で、過去の記憶を呼び覚ますきっかけとなるお菓子は何？", answers: ["マドレーヌ", "マカロン", "フィナンシェ", "カヌレ"], correctIndex: 0 },
  { category: "文学・芸術", difficulty: 4, question: "彫刻「考える人」の作者は誰？", answers: ["オーギュスト・ロダン", "ミケランジェロ", "ドナテッロ", "ジャン・ロレンツォ・ベルニーニ"], correctIndex: 0 },
  { category: "文学・芸術", difficulty: 4, question: "「叫び」を描いた画家の名前は？", answers: ["エドヴァルド・ムンク", "フィンセント・ファン・ゴッホ", "パブロ・ピカソ", "サルバドール・ダリ"], correctIndex: 0 },
  { category: "文学・芸術", difficulty: 5, question: "ジェイムズ・ジョイスの小説「ユリシーズ」は、どの古代ギリシャの叙事詩を下敷きにしている？", answers: ["オデュッセイア", "イリアス", "神統記", "労働と日々"], correctIndex: 0 },
  { category: "文学・芸術", difficulty: 5, question: "ミニマル・ミュージックの代表的な作曲家で、「アインシュタイン・オン・ザ・ビーチ」などのオペラで知られるのは誰？", answers: ["フィリップ・グラス", "スティーヴ・ライヒ", "テリー・ライリー", "ジョン・ケージ"], correctIndex: 0 },
  { category: "文学・芸術", difficulty: 5, question: "バレエ「白鳥の湖」を作曲したのは誰？", answers: ["チャイコフスキー", "ストラヴィンスキー", "プロコフィエフ", "ショスタコーヴィチ"], correctIndex: 0 },

  // --- カテゴリ: スポーツ ---
  { category: "スポーツ", difficulty: 1, question: "サッカーで1チームの競技人数は何人？", answers: ["11人", "9人", "7人", "5人"], correctIndex: 0 },
  { category: "スポーツ", difficulty: 1, question: "4年に一度開催される、スポーツの世界的な祭典といえば？", answers: ["オリンピック", "ワールドカップ", "世界選手権", "コモンウェルスゲームズ"], correctIndex: 0 },
  { category: "スポーツ", difficulty: 1, question: "野球で、3回ストライクを取られるとどうなる？", answers: ["アウト", "フォアボール", "ヒット", "ホームラン"], correctIndex: 0 },
  { category: "スポーツ", difficulty: 1, question: "バスケットボールのゴール（リング）の高さは、およそ何メートル？", answers: ["3メートル", "2.5メートル", "4メートル", "3.5メートル"], correctIndex: 0 },
  { category: "スポーツ", difficulty: 1, question: "日本の国技といえば何？", answers: ["相撲", "柔道", "剣道", "空手"], correctIndex: 0 },
  { category: "スポーツ", difficulty: 2, question: "マラソンの公式距離は42.195kmですが、これは何の戦いに由来する？", answers: ["マラトンの戦い", "テルモピュライの戦い", "サラミスの海戦", "プラタイアの戦い"], correctIndex: 0 },
  { category: "スポーツ", difficulty: 2, question: "テニスの4大大会（グランドスラム）に含まれないのはどれ？", answers: ["BNPパリバ・オープン", "全豪オープン", "全仏オープン", "ウィンブルドン選手権"], correctIndex: 0 },
  { category: "スポーツ", difficulty: 2, question: "アメリカのプロバスケットボールリーグの略称は？", answers: ["NBA", "MLB", "NFL", "NHL"], correctIndex: 0 },
  { category: "スポーツ", difficulty: 2, question: "陸上競技で「人類最速の男」の異名を持つ、ジャマイカの短距離選手は誰？", answers: ["ウサイン・ボルト", "カール・ルイス", "タイソン・ゲイ", "アサファ・パウエル"], correctIndex: 0 },
  { category: "スポーツ", difficulty: 2, question: "ラグビーで、ボールを前に落とす反則を何という？", answers: ["ノックオン", "スローフォワード", "オフサイド", "スクラム"], correctIndex: 0 },
  { category: "スポーツ", difficulty: 2, question: "サッカーで手を使える唯一のポジションは？", answers: ["ゴールキーパー", "ディフェンダー", "ミッドフィールダー", "フォワード"], correctIndex: 0 },
  { category: "スポーツ", difficulty: 3, question: "サッカーのワールドカップで、最も多く優勝している国は？", answers: ["ブラジル", "ドイツ", "イタリア", "アルゼンチン"], correctIndex: 0 },
  { category: "スポーツ", difficulty: 3, question: "ボクシングのヘビー級で「蝶のように舞い、蜂のように刺す」と評された伝説のチャンピオンは誰？", answers: ["モハメド・アリ", "マイク・タイソン", "ジョージ・フォアマン", "ロッキー・マルシアノ"], correctIndex: 0 },
  { category: "スポーツ", difficulty: 3, question: "ゴルフで、規定打数より1打少なくホールアウトすることを何という？", answers: ["バーディー", "パー", "ボギー", "イーグル"], correctIndex: 0 },
  { category: "スポーツ", difficulty: 3, question: "冬季オリンピックの競技でないものはどれ？", answers: ["水球", "カーリング", "バイアスロン", "リュージュ"], correctIndex: 0 },
  { category: "スポーツ", difficulty: 3, question: "F1で歴代最多の7度のワールドチャンピオンに輝いた記録を持つ2人のドライバーは、ミハエル・シューマッハと誰？", answers: ["ルイス・ハミルトン", "アイルトン・セナ", "アラン・プロスト", "セバスチャン・ベッテル"], correctIndex: 0 },
  { category: "スポーツ", difficulty: 3, question: "大相撲で、最高の番付（地位）を何という？", answers: ["横綱", "大関", "関脇", "小結"], correctIndex: 0 },
  { category: "スポーツ", difficulty: 3, question: "アメリカンフットボールで、攻撃側がゴールラインを越えて得点することを何という？", answers: ["タッチダウン", "ホームラン", "フィールドゴール", "トライ"], correctIndex: 0 },
  { category: "スポーツ", difficulty: 3, question: "スポーツで、一人の選手が1試合で3得点することを何という？", answers: ["ハットトリック", "トリプルダブル", "グランドスラム", "パーフェクトゲーム"], correctIndex: 0 },
  { category: "スポーツ", difficulty: 4, question: "ツール・ド・フランスで個人総合優勝者に贈られるジャージの色は？", answers: ["黄色（マイヨ・ジョーヌ）", "緑色（マイヨ・ヴェール）", "水玉模様（マイヨ・ブラン・ア・ポワ・ルージュ）", "白色（マイヨ・ブラン）"], correctIndex: 0 },
  { category: "スポーツ", difficulty: 4, question: "クリケットで、イギリスとオーストラリアが定期的に対戦するシリーズの名称は？", answers: ["ジ・アッシズ", "ザ・コモンウェルス", "ジ・アンザック", "ザ・ライバルリー"], correctIndex: 0 },
  { category: "スポーツ", difficulty: 4, question: "野球のメジャーリーグで、初めて黒人選手としてプレーし、人種の壁を打ち破った選手は誰？", answers: ["ジャッキー・ロビンソン", "ベーブ・ルース", "ウィリー・メイズ", "ハンク・アーロン"], correctIndex: 0 },
  { category: "スポーツ", difficulty: 4, question: "トライアスロンで行う3種目は、水泳、自転車と何？", answers: ["長距離走", "カヌー", "重量挙げ", "射撃"], correctIndex: 0 },
  { category: "スポーツ", difficulty: 4, question: "バスケットボールの神様と称される、シカゴ・ブルズで活躍した選手は？", answers: ["マイケル・ジョーダン", "レブロン・ジェームズ", "コービー・ブライアント", "マジック・ジョンソン"], correctIndex: 0 },
  { category: "スポーツ", difficulty: 5, question: "近代オリンピックの父と呼ばれるフランスの教育者は誰？", answers: ["ピエール・ド・クーベルタン", "アンリ・ディドロ", "ジャン・アンリ・デュナン", "ジャック・ロゲ"], correctIndex: 0 },
  { category: "スポーツ", difficulty: 5, question: "フェンシングの3種目のうち、有効面が全身となっているのはどれ？", answers: ["エペ", "フルーレ", "サーブル", "どれも違う"], correctIndex: 0 },

  // --- カテゴリ: 雑学 ---
  { category: "雑学", difficulty: 1, question: "信号機の「青」は、法律上では何色と定められている？", answers: ["緑色", "青色", "青緑色", "水色"], correctIndex: 0 },
  { category: "雑学", difficulty: 1, question: "1ダースは何個？", answers: ["12個", "10個", "20個", "6個"], correctIndex: 0 },
  { category: "雑学", difficulty: 1, question: "パンダの主食は何？", answers: ["笹", "ユーカリ", "果物", "肉"], correctIndex: 0 },
  { category: "雑学", difficulty: 1, question: "世界で最も多くの人に話されている言語は何？", answers: ["英語", "中国語（標準語）", "ヒンディー語", "スペイン語"], correctIndex: 0 },
  { category: "雑学", difficulty: 1, question: "お寿司で、ご飯の部分を何という？", answers: ["シャリ", "ネタ", "ガリ", "アガリ"], correctIndex: 0 },
  { category: "雑学", difficulty: 2, question: "タコの足は、一般的に何本と言われる？", answers: ["8本", "10本", "6本", "4本"], correctIndex: 0 },
  { category: "雑学", difficulty: 2, question: "ピアノの鍵盤の数は、一般的にいくつ？", answers: ["88鍵", "61鍵", "76鍵", "108鍵"], correctIndex: 0 },
  { category: "雑学", difficulty: 2, question: "「サザエさん」の夫、マスオさんの名字は何？", answers: ["フグ田", "磯野", "波野", "伊佐坂"], correctIndex: 0 },
  { category: "雑学", difficulty: 2, question: "世界三大珍味に含まれないものはどれ？", answers: ["フカヒレ", "キャビア", "フォアグラ", "トリュフ"], correctIndex: 0 },
  { category: "雑学", difficulty: 2, question: "鉛筆の芯の硬さを表す記号で、最も柔らかいのはどれ？", answers: ["B", "H", "F", "HB"], correctIndex: 0 },
  { category: "雑学", difficulty: 2, question: "日本の国花は、桜と何？", answers: ["菊", "梅", "椿", "朝顔"], correctIndex: 0 },
  { category: "雑学", difficulty: 2, question: "虹の最も外側にある色は何？", answers: ["赤", "紫", "青", "黄色"], correctIndex: 0 },
  { category: "雑学", difficulty: 3, question: "カメレオンの色が変わるのは、主に何のため？", answers: ["気分や体温の伝達", "背景に隠れるため", "敵を威嚇するため", "求愛のため"], correctIndex: 0 },
  { category: "雑学", difficulty: 3, question: "トランプのキングの中で、唯一口ひげがないのはどのキング？", answers: ["ハートのキング", "スペードのキング", "ダイヤのキング", "クラブのキング"], correctIndex: 0 },
  { category: "雑学", difficulty: 3, question: "「ミリ」、「センチ」、「デシ」。この中で最も大きい単位は？", answers: ["デシ", "センチ", "ミリ", "全部同じ"], correctIndex: 0 },
  { category: "雑学", difficulty: 3, question: "キリンの睡眠時間は、1日平均でどのくらい？", answers: ["約20分", "約8時間", "約4時間", "約12時間"], correctIndex: 0 },
  { category: "雑学", difficulty: 3, question: "元素記号にもなっているアインスタイニウム（Es）を発見するきっかけとなった出来事は？", answers: ["世界初の水爆実験", "チェルノブイリ原発事故", "太陽フレアの観測", "月の石の分析"], correctIndex: 0 },
  { category: "雑学", difficulty: 3, question: "コーヒー豆は、実際には何の種子？", answers: ["果実", "根", "葉", "花"], correctIndex: 0 },
  { category: "雑学", difficulty: 4, question: "世界で初めて缶コーヒーを発売した日本の企業は？", answers: ["上島珈琲貿易（UCC）", "ポッカ", "ダイドー", "サントリー"], correctIndex: 0 },
  { category: "雑学", difficulty: 4, question: "モース信号で「SOS」を表す符号は？", answers: ["・・・－－－・・・", "－－－・・・－－－", "・－・－・－", "－・・－・・－"], correctIndex: 0 },
  { category: "雑学", difficulty: 4, question: "ノーベル賞の6部門のうち、アルフレッド・ノーベルの遺言になかった部門は？", answers: ["経済学賞", "物理学賞", "化学賞", "平和賞"], correctIndex: 0 },
  { category: "雑学", difficulty: 4, question: "飛行機の「ブラックボックス」は、実際には何色？", answers: ["オレンジ色", "黒色", "黄色", "赤色"], correctIndex: 0 },
  { category: "雑学", difficulty: 4, question: "世界で初めてインスタントラーメンを発明した人物は？", answers: ["安藤百福", "盛田昭夫", "井深大", "本田宗一郎"], correctIndex: 0 },
  { category: "雑学", difficulty: 4, question: "食卓塩（塩化ナトリウム）の化学式は？", answers: ["NaCl", "H2O", "CO2", "C6H12O6"], correctIndex: 0 },
  { category: "雑学", difficulty: 5, question: "バーコードの黒い線の隣にある、白い線の部分を何と呼ぶ？", answers: ["スペース", "バー", "ギャップ", "ライン"], correctIndex: 0 },
  { category: "雑学", difficulty: 5, question: "十二支の中で、唯一架空の動物は「辰（龍）」ですが、その「辰」の時刻は何時ごろ？", answers: ["午前8時ごろ", "午前0時ごろ", "正午ごろ", "午後4時ごろ"], correctIndex: 0 },
  
  // --- カテゴリ: 動物 (Animals) ---
  { category: "動物", difficulty: 1, question: "「百獣の王」と呼ばれる動物は何？", answers: ["ライオン", "トラ", "ゾウ", "ゴリラ"], correctIndex: 0 },
  { category: "動物", difficulty: 1, question: "世界で最も背の高い動物は何？", answers: ["キリン", "ゾウ", "ダチョウ", "ウマ"], correctIndex: 0 },
  { category: "動物", difficulty: 1, question: "オーストラリアに生息する、お腹の袋で子供を育てる有袋類は？", answers: ["カンガルー", "コアラ", "ウォンバット", "タスマニアデビル"], correctIndex: 0 },
  { category: "動物", difficulty: 1, question: "鳥類で最も大きく、飛べない鳥として知られるのは？", answers: ["ダチョウ", "ペンギン", "エミュー", "ヒクイドリ"], correctIndex: 0 },
  { category: "動物", difficulty: 1, question: "冬になると冬眠するクマ。英語で何という？", answers: ["Bear", "Wolf", "Fox", "Deer"], correctIndex: 0 },
  { category: "動物", difficulty: 2, question: "地球上で最大の動物は何？", answers: ["シロナガスクジラ", "アフリカゾウ", "ジンベエザメ", "ダイオウイカ"], correctIndex: 0 },
  { category: "動物", difficulty: 2, question: "8本の腕（足）を持つ海洋生物は何？", answers: ["タコ", "イカ", "ヒトデ", "ウニ"], correctIndex: 0 },
  { category: "動物", difficulty: 2, question: "ネコ科の動物で、地上最速の哺乳類は？", answers: ["チーター", "ライオン", "ヒョウ", "ピューマ"], correctIndex: 0 },
  { category: "動物", difficulty: 2, question: "一度にたくさんの卵を産むことで知られる魚は？", answers: ["マンボウ", "マグロ", "サケ", "コイ"], correctIndex: 0 },
  { category: "動物", difficulty: 3, question: "卵を産む珍しい哺乳類、カモノハシが持つ感覚器官は？", answers: ["電気受容", "超音波", "赤外線感知", "磁気コンパス"], correctIndex: 0 },
  { category: "動物", difficulty: 3, question: "「生きた化石」とも呼ばれる、深海に生息する古代魚は？", answers: ["シーラカンス", "チョウザメ", "ラブカ", "ミツクリザメ"], correctIndex: 0 },
  { category: "動物", difficulty: 3, question: "集団で狩りをする、非常に社会性の高いイヌ科の動物は？", answers: ["オオカミ", "ハイエナ", "リカオン", "ジャッカル"], correctIndex: 0 },
  { category: "動物", difficulty: 3, question: "自分の目玉をなめることができる唯一の哺乳類は何？", answers: ["キリン", "カメレオン", "ヤモリ", "ネコ"], correctIndex: 0 },
  { category: "動物", difficulty: 4, question: "毒を持つことで知られる、世界最小の鳥は何？", answers: ["ズアオチメドリ", "ハチドリ", "ミソサザイ", "キクイタダキ"], correctIndex: 0 },
  { category: "動物", difficulty: 4, question: "自分の体重の何倍もの重さのものを持ち上げることができる昆虫は？", answers: ["アリ", "カブトムシ", "ハチ", "バッタ"], correctIndex: 0 },
  { category: "動物", difficulty: 5, question: "不老不死とも言われ、若返ることができるクラゲは？", answers: ["ベニクラゲ", "ミズクラゲ", "アカクラゲ", "ハブクラゲ"], correctIndex: 0 },

  // --- カテゴリ: 食べ物 (Food & Drink) ---
  { category: "食べ物", difficulty: 1, question: "イタリア料理の代表格で、薄い生地に具材を乗せて焼いたものは？", answers: ["ピザ", "パスタ", "リゾット", "ラザニア"], correctIndex: 0 },
  { category: "食べ物", difficulty: 1, question: "日本の代表的な麺料理で、小麦粉から作られるのは？", answers: ["うどん", "そば", "ラーメン", "そうめん"], correctIndex: 0 },
  { category: "食べ物", difficulty: 1, question: "フランスパンの代表的な種類で、細長い形状が特徴なのは？", answers: ["バゲット", "クロワッサン", "パン・ド・カンパーニュ", "ブリオッシュ"], correctIndex: 0 },
  { category: "食べ物", difficulty: 1, question: "朝食の定番で、鶏の卵を焼いた料理は？", answers: ["目玉焼き", "オムレツ", "スクランブルエッグ", "だし巻き卵"], correctIndex: 0 },
  { category: "食べ物", difficulty: 1, question: "チョコレートの主な原料は何？", answers: ["カカオ豆", "コーヒー豆", "大豆", "アーモンド"], correctIndex: 0 },
  { category: "食べ物", difficulty: 2, question: "スペイン料理で、米と魚介類などを一緒に炊き込んだものは？", answers: ["パエリア", "タパス", "ガスパチョ", "アヒージョ"], correctIndex: 0 },
  { category: "食べ物", difficulty: 2, question: "インド料理で、様々なスパイスを使って煮込んだ料理を何と総称する？", answers: ["カレー", "タンドリー", "ビリヤニ", "サモサ"], correctIndex: 0 },
  { category: "食べ物", difficulty: 2, question: "寿司で、シャリを覆う魚介類などの具材を何という？", answers: ["ネタ", "シャリ", "ガリ", "アガリ"], correctIndex: 0 },
  { category: "食べ物", difficulty: 2, question: "ワインの原料となる果物は何？", answers: ["ブドウ", "リンゴ", "モモ", "イチゴ"], correctIndex: 0 },
  { category: "食べ物", difficulty: 3, question: "世界三大スープの一つで、タイの辛くて酸っぱいエビのスープは？", answers: ["トムヤムクン", "ボルシチ", "ブイヤベース", "フカヒレスープ"], correctIndex: 0 },
  { category: "食べ物", difficulty: 3, question: "発酵させたキャベツを使ったドイツの代表的な付け合わせは？", answers: ["ザワークラウト", "ピクルス", "キムチ", "コールスロー"], correctIndex: 0 },
  { category: "食べ物", difficulty: 3, question: "チーズを作る過程で、牛乳を固めるために使われる酵素は？", answers: ["レンネット", "ペプシン", "アミラーゼ", "リパーゼ"], correctIndex: 0 },
  { category: "食べ物", difficulty: 3, question: "唐辛子の辛さの単位を何という？", answers: ["スコヴィル値", "カプサイシン度", "ブリックス度", "ボーメ度"], correctIndex: 0 },
  { category: "食べ物", difficulty: 4, question: "フグの毒の主成分である神経毒の名前は？", answers: ["テトロドトキシン", "サキシトキシン", "ソラニン", "シガテラ"], correctIndex: 0 },
  { category: "食べ物", difficulty: 4, question: "世界で最も高価なスパイスの一つで、花のめしべから採れるのは？", answers: ["サフラン", "バニラ", "カルダモン", "クローブ"], correctIndex: 0 },
  { category: "食べ物", difficulty: 5, question: "コーヒー豆の焙煎度合いで、最も浅煎りのものを何と呼ぶ？", answers: ["ライトロースト", "フレンチロースト", "イタリアンロースト", "フルシティロースト"], correctIndex: 0 },

  // --- カテゴリ: 音楽 ---
  { category: "音楽", difficulty: 1, question: "オーケストラで、指揮者が振る棒を何という？", answers: ["指揮棒（タクト）", "バトン", "ワンド", "スティック"], correctIndex: 0 },
  { category: "音楽", difficulty: 1, question: "ピアノの鍵盤は、白と黒の2色ですが、標準的な数はいくつ？", answers: ["88鍵", "61鍵", "76鍵", "108鍵"], correctIndex: 0 },
  { category: "音楽", difficulty: 1, question: "「ドレミファソラシド」は、どの国の音名？", answers: ["イタリア", "ドイツ", "イギリス", "日本"], correctIndex: 0 },
  { category: "音楽", difficulty: 2, question: "クラシック音楽の「四大作曲家」と言えば、バッハ、ベートーヴェン、モーツァルトと誰？", answers: ["ブラームス", "ハイドン", "シューベルト", "ショパン"], correctIndex: 0 },
  { category: "音楽", difficulty: 2, question: "ジャズ音楽で、即興演奏のことを何という？", answers: ["インプロヴィゼーション", "アレンジメント", "コンポジション", "モジュレーション"], correctIndex: 0 },
  { category: "音楽", difficulty: 2, question: "ロックバンドの基本的な編成で、ボーカル、ギター、ベースとあと一つは？", answers: ["ドラム", "キーボード", "サックス", "トランペット"], correctIndex: 0 },
  { category: "音楽", difficulty: 3, question: "「ボヘミアン・ラプソディ」で有名なイギリスのロックバンドは？", answers: ["クイーン", "ザ・ビートルズ", "ローリング・ストーンズ", "レッド・ツェッペリン"], correctIndex: 0 },
  { category: "音楽", difficulty: 3, question: "楽譜で、ト音記号が示す音は何？", answers: ["ソ（G）", "ド（C）", "ファ（F）", "ラ（A）"], correctIndex: 0 },
  { category: "音楽", difficulty: 4, question: "現代音楽の技法の一つで、音の高さ、長さ、強さなどを数列に基づいて作曲する方法は？", answers: ["セリエル音楽", "偶然性の音楽", "ミニマル・ミュージック", "電子音楽"], correctIndex: 0 },
  { category: "音楽", difficulty: 4, question: "エレキギターの音を歪ませるエフェクターの代表格は何？", answers: ["オーバードライブ", "ディレイ", "リバーブ", "コーラス"], correctIndex: 0 },
  { category: "音楽", difficulty: 4, question: "「四季」を作曲したイタリアの作曲家は？", answers: ["ヴィヴァルディ", "コレッリ", "アルビノーニ", "スカルラッティ"], correctIndex: 0 },
  { category: "音楽", difficulty: 5, question: "ジョン・ケージが作曲した、演奏者が何も演奏しない「4分33秒」が問いかけるものは？", answers: ["環境音や沈黙も音楽であること", "演奏者の技術", "楽譜の絶対性", "著作権の概念"], correctIndex: 0 },

  // --- カテゴリ: 映画 ---
  { category: "映画", difficulty: 1, question: "アカデミー賞で、最も栄誉あるとされる賞は何賞？", answers: ["作品賞", "監督賞", "主演男優賞", "脚本賞"], correctIndex: 0 },
  { category: "映画", difficulty: 1, question: "「E.T.」や「ジュラシック・パーク」を監督した有名な映画監督は？", answers: ["スティーヴン・スピルバーグ", "ジョージ・ルーカス", "ジェームズ・キャメロン", "クリストファー・ノーラン"], correctIndex: 0 },
  { category: "映画", difficulty: 1, question: "ディズニーの長編アニメーションで、主人公がライオンの映画は？", answers: ["ライオン・キング", "アラジン", "美女と野獣", "リトル・マーメイド"], correctIndex: 0 },
  { category: "映画", difficulty: 2, question: "「タイタニック」でヒロインのローズを演じた女優は？", answers: ["ケイト・ウィンスレット", "アンジェリーナ・ジョリー", "ジュリア・ロバーツ", "ニコール・キッドマン"], correctIndex: 0 },
  { category: "映画", difficulty: 2, question: "「スター・ウォーズ」シリーズで、ダース・ベイダーの正体は？", answers: ["アナキン・スカイウォーカー", "ルーク・スカイウォーカー", "オビ＝ワン・ケノービ", "パルパティーン皇帝"], correctIndex: 0 },
  { category: "映画", difficulty: 2, question: "スタジオジブリの映画で、不思議な生き物「トトロ」が登場する作品の監督は誰？", answers: ["宮崎駿", "高畑勲", "鈴木敏夫", "庵野秀明"], correctIndex: 0 },
  { category: "映画", difficulty: 3, question: "クエンティン・タランティーノ監督の映画で、時系列がシャッフルされていることで有名な作品は？", answers: ["パルプ・フィクション", "レザボア・ドッグス", "キル・ビル", "イングロリアス・バスターズ"], correctIndex: 0 },
  { category: "映画", difficulty: 3, question: "「007」シリーズで、ジェームズ・ボンドが所属するイギリスの諜報機関は？", answers: ["MI6", "CIA", "KGB", "モサド"], correctIndex: 0 },
  { category: "映画", difficulty: 3, question: "映画「ゴッドファーザー」の監督は誰？", answers: ["フランシス・フォード・コッポラ", "マーティン・スコセッシ", "スティーヴン・スピルバーグ", "アルフレッド・ヒッチコック"], correctIndex: 0 },
  { category: "映画", difficulty: 4, question: "映画の撮影技法で、被写体はそのままで背景だけが動いているように見せる合成技術は？", answers: ["バックプロジェクション", "マットペインティング", "クロマキー合成", "モーションキャプチャ"], correctIndex: 0 },
  { category: "映画", difficulty: 4, question: "ヒッチコック監督の映画「サイコ」で、観客を驚かせた有名なシャワーシーン。その音楽を担当した作曲家は？", answers: ["バーナード・ハーマン", "ジョン・ウィリアムズ", "エンニオ・モリコーネ", "ハンス・ジマー"], correctIndex: 0 },
  { category: "映画", difficulty: 5, question: "フィルム・ノワールの特徴として、当てはまらないものはどれ？", answers: ["ハッピーエンド", "退廃的な雰囲気", "影を多用した照明", "運命の女（ファム・ファタール）"], correctIndex: 0 },

  // --- カテゴリ: 神話・伝承 ---
  { category: "神話・伝承", difficulty: 1, question: "ギリシャ神話の主神で、雷を操るのは誰？", answers: ["ゼウス", "ポセイドン", "ハデス", "アポロン"], correctIndex: 0 },
  { category: "神話・伝承", difficulty: 1, question: "日本の昔話で、大きな桃から生まれた英雄は？", answers: ["桃太郎", "金太郎", "浦島太郎", "一寸法師"], correctIndex: 0 },
  { category: "神話・伝承", difficulty: 1, question: "北欧神話で、強力なハンマー「ミョルニル」を使う神は？", answers: ["トール", "オーディン", "ロキ", "フレイ"], correctIndex: 0 },
  { category: "神話・伝承", difficulty: 2, question: "エジプト神話で、死者の魂を裁く、ジャッカルの頭を持つ神は？", answers: ["アヌビス", "オシリス", "ホルス", "ラー"], correctIndex: 0 },
  { category: "神話・伝承", difficulty: 2, question: "見たものを石に変える能力を持つ、ギリシャ神話の怪物は？", answers: ["メドゥーサ", "キマイラ", "ミノタウロス", "ヒュドラ"], correctIndex: 0 },
  { category: "神話・伝承", difficulty: 2, question: "アイルランドの伝承で、聖パトリックの日にシンボルとされる、三つ葉の植物は何？", answers: ["シャムロック", "クローバー", "オーク", "イチイ"], correctIndex: 0 },
  { category: "神話・伝承", difficulty: 3, question: "インド神話で、世界を創造し、維持し、破壊する三最高神（トリムルティ）に含まれないのは？", answers: ["インドラ", "ブラフマー", "ヴィシュヌ", "シヴァ"], correctIndex: 0 },
  { category: "神話・伝承", difficulty: 3, question: "アーサー王伝説で、アーサー王が湖の乙女から授かった聖剣の名前は？", answers: ["エクスカリバー", "クラレント", "アロンダイト", "ガラティン"], correctIndex: 0 },
  { category: "神話・伝承", difficulty: 3, question: "日本の妖怪で、頭に皿を乗せているのは？", answers: ["河童", "天狗", "鬼", "座敷童子"], correctIndex: 0 },
  { category: "神話・伝承", difficulty: 4, question: "メソポタミア神話の「ギルガメシュ叙事詩」で、大洪水を生き延びた賢者の名前は？", answers: ["ウトナピシュティム", "エンキドゥ", "フンババ", "イシュタル"], correctIndex: 0 },
  { category: "神話・伝承", difficulty: 4, question: "日本の神話で、天照大神が隠れたとされる場所は？", answers: ["天岩戸", "高天原", "黄泉の国", "葦原の中つ国"], correctIndex: 0 },
  { category: "神話・伝承", difficulty: 5, question: "北欧神話における世界の終わり、神々の最終戦争を何という？", answers: ["ラグナロク", "ゲッターデメルング", "アルマゲドン", "ヴァルハラ"], correctIndex: 0 }
];